### Creating series

In [60]:
import numpy as np
import pandas as pd

In [61]:
labels = [ 'a', 'b', 'c' ]
my_data = [ 10, 20, 30 ]
arr = np.array(my_data)
d = { 'a': 10, 'b': 20, 'c': 30 }
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [62]:
pd.Series(my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [63]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [64]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Creating a data frame

In [65]:
data = {
    'name': ['vinay', 'john', 'michael' , 'susan'],
    'age': [25, 30, 35, 40],    
    'salary': [ 100000, 60000, 70000, 80000],
    'city': ['germany', 'usa', 'india', 'uk']
}
pd.DataFrame(data)

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

In [66]:
data_list = [
    ['vinay', 25, 100000, 'germany'],
    ['john', 30, 60000, 'usa'],
    ['michael', 35, 70000, 'india'],
    ['susan', 40, 80000, 'uk'   ]
]
df2 = pd.DataFrame(data_list, columns=['name', 'age', 'salary', 'city'])
df2

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

### Selection and indexing of columns

In [67]:
df2

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

In [68]:
df2[['name', 'city']]

      name     city
0    vinay  germany
1     john      usa
2  michael    india
3    susan       uk

### creating a new columns

In [69]:
df2['designation'] = ['data scientist', 'developer', 'analyst', 'consultant']
df2

      name  age  salary     city     designation
0    vinay   25  100000  germany  data scientist
1     john   30   60000      usa       developer
2  michael   35   70000    india         analyst
3    susan   40   80000       uk      consultant

### remove a column

In [70]:
df2.drop('designation', axis=1, inplace =True)

In [71]:
df2

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

### selecting rows

In [72]:
df2

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

In [73]:
df2.loc[[0, 1]]

    name  age  salary     city
0  vinay   25  100000  germany
1   john   30   60000      usa

In [74]:
df2.iloc[0]

name        vinay
age            25
salary     100000
city      germany
Name: 0, dtype: object

In [75]:
df2.loc[[0,1]] [['city', 'salary']]

      city  salary
0  germany  100000
1      usa   60000

In [76]:
df2.loc[[2,3]][['name', 'age']]

      name  age
2  michael   35
3    susan   40

### conditional selection

In [77]:
df2

      name  age  salary     city
0    vinay   25  100000  germany
1     john   30   60000      usa
2  michael   35   70000    india
3    susan   40   80000       uk

In [78]:
df2[df2['age'] > 30]

      name  age  salary   city
2  michael   35   70000  india
3    susan   40   80000     uk

In [79]:
df2[(df2['age'] > 30) & (df2['salary'] == 80000)]

    name  age  salary city
3  susan   40   80000   uk

### MISSING DATA

#### finding  missing data

In [80]:
data = {
    'name': ['vinay', np.nan, 'michael' , 'susan'],
    'age': [25, 30, 35, np.nan],    
    'salary': [ 100000, 60000, np.nan, 80000],
    'city': ['germany', 'usa', 'india', np.nan]
}
df3 = pd.DataFrame(data)
df3

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india
3    susan   NaN   80000.0      NaN

In [81]:
df3.isna()

    name    age  salary   city
0  False  False   False  False
1   True  False   False  False
2  False  False    True  False
3  False   True   False   True

In [82]:
df3.isna().sum()

name      1
age       1
salary    1
city      1
dtype: int64

In [83]:
df3.isna().any()

name      True
age       True
salary    True
city      True
dtype: bool

#### removing missing data

In [84]:
df3

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india
3    susan   NaN   80000.0      NaN

In [85]:
df3.dropna()

    name   age    salary     city
0  vinay  25.0  100000.0  germany

In [86]:
df3

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india
3    susan   NaN   80000.0      NaN

In [87]:
df3.dropna(thresh=3)

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india

#### filling missing data

In [88]:
df3

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india
3    susan   NaN   80000.0      NaN

In [89]:
df3.fillna(value='missing')

      name      age    salary     city
0    vinay     25.0  100000.0  germany
1  missing     30.0   60000.0      usa
2  michael     35.0   missing    india
3    susan  missing   80000.0  missing

In [90]:
df3

      name   age    salary     city
0    vinay  25.0  100000.0  germany
1      NaN  30.0   60000.0      usa
2  michael  35.0       NaN    india
3    susan   NaN   80000.0      NaN

### MERGING , JOINING , CONCATINATION

#### merging of 2 dataframes

In [91]:
employee = pd.DataFrame({
    'employee_id': [ 1, 2, 3, 4, 5],
    'name' : ['john', 'aman' , 'gotam', 'sumit', 'vinay'],
    'department': ['hr', 'operation', 'marketing', 'manager', 'data scentist']
})

salaries =pd.DataFrame({
    'employee_id':[ 1, 2, 3, 6, 7],
    'salary': [30000, 40000, 50000, 60000, 100000],
    'bonus': [20000, 30000, 40000, 30000, 60000]
})

In [92]:
employee

   employee_id   name     department
0            1   john             hr
1            2   aman      operation
2            3  gotam      marketing
3            4  sumit        manager
4            5  vinay  data scentist

In [93]:
salaries

   employee_id  salary  bonus
0            1   30000  20000
1            2   40000  30000
2            3   50000  40000
3            6   60000  30000
4            7  100000  60000

In [94]:
pd.merge(employee,salaries,on= 'employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   john         hr   30000  20000
1            2   aman  operation   40000  30000
2            3  gotam  marketing   50000  40000

In [95]:
pd.merge(employee,salaries,on= 'employee_id', how='outer')

   employee_id   name     department    salary    bonus
0            1   john             hr   30000.0  20000.0
1            2   aman      operation   40000.0  30000.0
2            3  gotam      marketing   50000.0  40000.0
3            4  sumit        manager       NaN      NaN
4            5  vinay  data scentist       NaN      NaN
5            6    NaN            NaN   60000.0  30000.0
6            7    NaN            NaN  100000.0  60000.0

In [96]:
pd.merge(employee,salaries,on= 'employee_id', how='left')

   employee_id   name     department   salary    bonus
0            1   john             hr  30000.0  20000.0
1            2   aman      operation  40000.0  30000.0
2            3  gotam      marketing  50000.0  40000.0
3            4  sumit        manager      NaN      NaN
4            5  vinay  data scentist      NaN      NaN

In [97]:
pd.merge(employee,salaries,on= 'employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   john         hr   30000  20000
1            2   aman  operation   40000  30000
2            3  gotam  marketing   50000  40000
3            6    NaN        NaN   60000  30000
4            7    NaN        NaN  100000  60000

#### concatination of 2 dataframes

In [98]:
df1=pd.DataFrame ({
    'a':['a0', 'a1', 'a2'],
    'b':['b0','b1', 'b2'],
    'c':['c0', 'c1', 'c2']
})

df2=pd.DataFrame({
    'a':['a3','a4', 'a5'],
    'b':['b3', 'b4', 'b5'],
    'c':['c3', 'c4', 'c5']
})

In [99]:
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [100]:
df2

    a   b   c
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

In [101]:
pd.concat([df1,df2])

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

In [102]:
pd.concat([df1,df2 ],axis=1)

    a   b   c   a   b   c
0  a0  b0  c0  a3  b3  c3
1  a1  b1  c1  a4  b4  c4
2  a2  b2  c2  a5  b5  c5

#### joining of 2 dataframes

In [103]:
df1= pd.DataFrame ({
    'name': ['ben', 'gwen', 'kevin']
},index=[1, 2, 3])

df2=pd.DataFrame({
    'score':[95, 98, 94]
},index=[2, 3, 4])

In [104]:
df1

    name
1    ben
2   gwen
3  kevin

In [105]:
df2

   score
2     95
3     98
4     94

In [106]:
df1.join(df2, how='outer')

    name  score
1    ben    NaN
2   gwen   95.0
3  kevin   98.0
4    NaN   94.0

### groupby aggregation

In [107]:
data = {
    'category': ['a', 'b', 'c', 'a', 'b', 'a', 'b'],
    'store' : [ 's1', 's2', 's2', 's1', 's1', 's2', 's1'],
    'sales': [100, 200, 300, 100, 150, 250, 100],
    'quantity': [10, 20, 15, 12, 15, 8, 17],
    'date': pd.date_range('2026-2-2', periods=7)
}
df =pd.DataFrame(data)

In [108]:
df

  category store  sales  quantity       date
0        a    s1    100        10 2026-02-02
1        b    s2    200        20 2026-02-03
2        c    s2    300        15 2026-02-04
3        a    s1    100        12 2026-02-05
4        b    s1    150        15 2026-02-06
5        a    s2    250         8 2026-02-07
6        b    s1    100        17 2026-02-08

In [109]:
cat= df.groupby('category')['sales'].sum()
cat

category
a    450
b    450
c    300
Name: sales, dtype: int64

In [110]:
cat= df.groupby('store')['sales'].sum()
cat

store
s1    450
s2    750
Name: sales, dtype: int64

In [111]:
cat= df.groupby(['store', 'category'])['sales'].sum()
cat

store  category
s1     a           200
       b           250
s2     a           250
       b           200
       c           300
Name: sales, dtype: int64

### aggregation

In [112]:
df['sales'].mean()

np.float64(171.42857142857142)

In [113]:
df['sales'].agg(['mean', 'sum', 'max', 'min', ])

mean     171.428571
sum     1200.000000
max      300.000000
min      100.000000
Name: sales, dtype: float64

### pivot tables

In [116]:
data ={
    'date': pd.date_range('2026-2-2', periods=20),
    'product': (['A', 'B', 'C'] * 7) [:20],
    'region': ['north', 'south', 'east', 'west'] * 5,
    'sale': np.random.randint(100, 1000, 20),
    'unit': np.random.randint(1, 10, 20),
    'rep' : ['john', 'bob', 'mary', 'alice'] * 5,


    }

df= pd.DataFrame(data)
df['month'] = df['date'].dt.month_name()
df['quarter'] = '0' + df['date'].dt.quarter.astype(str)
df

         date product region  sale  unit    rep     month quarter
0  2026-02-02       A  north   985     3   john  February      01
1  2026-02-03       B  south   543     4    bob  February      01
2  2026-02-04       C   east   389     1   mary  February      01
3  2026-02-05       A   west   435     3  alice  February      01
4  2026-02-06       B  north   224     9   john  February      01
5  2026-02-07       C  south   772     3    bob  February      01
6  2026-02-08       A   east   134     4   mary  February      01
7  2026-02-09       B   west   747     1  alice  February      01
8  2026-02-10       C  north   920     9   john  February      01
9  2026-02-11       A  south   864     5    bob  February      01
10 2026-02-12       B   east   957     7   mary  February      01
11 2026-02-13       C   west   302     5  alice  February      01
12 2026-02-14       A  north   983     3   john  February      01
13 2026-02-15       B  south   315     8    bob  February      01
14 2026-02-16       C   east   433     3   mary  February      01
15 2026-02-17       A   west   176     7  alice  February      01
16 2026-02-18       B  north   296     1   john  February      01
17 2026-02-19       C  south   946     7    bob  February      01
18 2026-02-20       A   east   133     7   mary  February      01
19 2026-02-21       B   west   639     8  alice  February      01

In [120]:
pd.pivot_table(df,values='sale', index='region', columns='product', aggfunc='median')

product      A      B      C
region
east     133.5  957.0  411.0
north    984.0  260.0  920.0
south    864.0  429.0  859.0
west     305.5  693.0  302.0

In [121]:
pivot2= pd.pivot_table(df,values=['sale','unit'], index='region', columns='product', )
pivot2

          sale               unit
product      A      B      C    A    B    C
region
east     133.5  957.0  411.0  5.5  7.0  2.0
north    984.0  260.0  920.0  3.0  5.0  9.0
south    864.0  429.0  859.0  5.0  6.0  5.0
west     305.5  693.0  302.0  5.0  4.5  5.0

#### cross tabs

In [123]:
pd.crosstab(df['region'], df['product'], )

product  A  B  C
region
east     2  1  2
north    2  2  1
south    1  2  2
west     2  2  1

### operations

#### dataframes basic operations

In [125]:
df1= pd.DataFrame({
    'name': ['john', 'bob', 'mary', 'alice'],
    'score': [95, 98, 94, 97]
})
df1

    name  score
0   john     95
1    bob     98
2   mary     94
3  alice     97

In [126]:
df1.shape

(4, 2)

In [127]:
df1.columns

Index(['name', 'score'], dtype='object')

In [128]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   score   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [129]:
df1.describe()

           score
count   4.000000
mean   96.000000
std     1.825742
min    94.000000
25%    94.750000
50%    96.000000
75%    97.250000
max    98.000000

In [130]:
df1['score'] +10

0    105
1    108
2    104
3    107
Name: score, dtype: int64

#### dataframes applying function

In [132]:
df1['score'].rank()

0    2.0
1    4.0
2    1.0
3    3.0
Name: score, dtype: float64

In [133]:
df1

    name  score
0   john     95
1    bob     98
2   mary     94
3  alice     97

In [134]:
def square(x):
    return x**2

df1['score'].apply(square)

0    9025
1    9604
2    8836
3    9409
Name: score, dtype: int64

In [135]:
df1['square_score'] = df1['score'].apply(square)

In [138]:
df1

    name  score  square_score
0   john     95          9025
1    bob     98          9604
2   mary     94          8836
3  alice     97          9409